version: "3"

services:
  jekyll:
      image: jekyll/jekyll:latest
      command: jekyll serve --watch --force_polling --host 0.0.0.0 --port 8000
      ports:
        - 8000:8000
      volumes:
        - .:/srv/jekyll
